package com.github.flux.entity;

public class Appointment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.appointment_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long appointmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.type_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.name
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.logo
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.target_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long targetNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.begin_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.end_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.standard
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String standard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.declaration
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String declaration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.flux_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long fluxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.only_friend
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer onlyFriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.push_friend
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer pushFriend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.enroll_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long enrollNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.view_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long viewNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment.enroll_userids
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String enrollUserids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.appointment_id
     *
     * @return the value of appointment.appointment_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getAppointmentId() {
        return appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.appointment_id
     *
     * @param appointmentId the value for appointment.appointment_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setAppointmentId(Long appointmentId) {
        this.appointmentId = appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.userid
     *
     * @return the value of appointment.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.userid
     *
     * @param userid the value for appointment.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.type_id
     *
     * @return the value of appointment.type_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.type_id
     *
     * @param typeId the value for appointment.type_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.name
     *
     * @return the value of appointment.name
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.name
     *
     * @param name the value for appointment.name
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.logo
     *
     * @return the value of appointment.logo
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.logo
     *
     * @param logo the value for appointment.logo
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.target_num
     *
     * @return the value of appointment.target_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getTargetNum() {
        return targetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.target_num
     *
     * @param targetNum the value for appointment.target_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setTargetNum(Long targetNum) {
        this.targetNum = targetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.begin_time
     *
     * @return the value of appointment.begin_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.begin_time
     *
     * @param beginTime the value for appointment.begin_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setBeginTime(Long beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.end_time
     *
     * @return the value of appointment.end_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.end_time
     *
     * @param endTime the value for appointment.end_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.standard
     *
     * @return the value of appointment.standard
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.standard
     *
     * @param standard the value for appointment.standard
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.declaration
     *
     * @return the value of appointment.declaration
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.declaration
     *
     * @param declaration the value for appointment.declaration
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setDeclaration(String declaration) {
        this.declaration = declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.flux_num
     *
     * @return the value of appointment.flux_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getFluxNum() {
        return fluxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.flux_num
     *
     * @param fluxNum the value for appointment.flux_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setFluxNum(Long fluxNum) {
        this.fluxNum = fluxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.only_friend
     *
     * @return the value of appointment.only_friend
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getOnlyFriend() {
        return onlyFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.only_friend
     *
     * @param onlyFriend the value for appointment.only_friend
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setOnlyFriend(Integer onlyFriend) {
        this.onlyFriend = onlyFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.push_friend
     *
     * @return the value of appointment.push_friend
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getPushFriend() {
        return pushFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.push_friend
     *
     * @param pushFriend the value for appointment.push_friend
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setPushFriend(Integer pushFriend) {
        this.pushFriend = pushFriend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.enroll_num
     *
     * @return the value of appointment.enroll_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getEnrollNum() {
        return enrollNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.enroll_num
     *
     * @param enrollNum the value for appointment.enroll_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setEnrollNum(Long enrollNum) {
        this.enrollNum = enrollNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.view_num
     *
     * @return the value of appointment.view_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getViewNum() {
        return viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.view_num
     *
     * @param viewNum the value for appointment.view_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setViewNum(Long viewNum) {
        this.viewNum = viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.create_time
     *
     * @return the value of appointment.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.create_time
     *
     * @param createTime the value for appointment.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.status
     *
     * @return the value of appointment.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.status
     *
     * @param status the value for appointment.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment.enroll_userids
     *
     * @return the value of appointment.enroll_userids
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getEnrollUserids() {
        return enrollUserids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment.enroll_userids
     *
     * @param enrollUserids the value for appointment.enroll_userids
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setEnrollUserids(String enrollUserids) {
        this.enrollUserids = enrollUserids;
    }
}