package com.github.flux.entity;

import java.io.Serializable;

public class Donation implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.id
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.fromuserid
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    private Long fromuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.touserid
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    private Long touserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.num
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.create_time
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column donation.msg_id
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    private Long msgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.id
     *
     * @return the value of donation.id
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.id
     *
     * @param id the value for donation.id
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.fromuserid
     *
     * @return the value of donation.fromuserid
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public Long getFromuserid() {
        return fromuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.fromuserid
     *
     * @param fromuserid the value for donation.fromuserid
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public void setFromuserid(Long fromuserid) {
        this.fromuserid = fromuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.touserid
     *
     * @return the value of donation.touserid
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public Long getTouserid() {
        return touserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.touserid
     *
     * @param touserid the value for donation.touserid
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public void setTouserid(Long touserid) {
        this.touserid = touserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.num
     *
     * @return the value of donation.num
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.num
     *
     * @param num the value for donation.num
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.create_time
     *
     * @return the value of donation.create_time
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.create_time
     *
     * @param createTime the value for donation.create_time
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column donation.msg_id
     *
     * @return the value of donation.msg_id
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column donation.msg_id
     *
     * @param msgId the value for donation.msg_id
     *
     * @mbggenerated Mon Aug 24 00:46:54 CST 2015
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

	@Override
	public String toString() {
		return "Donation [id=" + id + ", fromuserid=" + fromuserid + ", touserid=" + touserid + ", num=" + num
				+ ", createTime=" + createTime + ", msgId=" + msgId + "]";
	}
    
    
}