package com.github.flux.entity;

import java.io.Serializable;
import java.util.Date;

public class Log implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.username
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.module
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.action
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.action_time
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private String actionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_ip
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.oper_time
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    private Date operTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.username
     *
     * @return the value of log.username
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.username
     *
     * @param username the value for log.username
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.module
     *
     * @return the value of log.module
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.module
     *
     * @param module the value for log.module
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.action
     *
     * @return the value of log.action
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.action
     *
     * @param action the value for log.action
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.action_time
     *
     * @return the value of log.action_time
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public String getActionTime() {
        return actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.action_time
     *
     * @param actionTime the value for log.action_time
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setActionTime(String actionTime) {
        this.actionTime = actionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_ip
     *
     * @return the value of log.user_ip
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_ip
     *
     * @param userIp the value for log.user_ip
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.oper_time
     *
     * @return the value of log.oper_time
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.oper_time
     *
     * @param operTime the value for log.oper_time
     *
     * @mbggenerated Thu Aug 13 21:57:45 CST 2015
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }
}