package com.github.flux.entity;

import java.io.Serializable;

public class Message implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msg_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long msgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.template
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msg_id
     *
     * @return the value of message.msg_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msg_id
     *
     * @param msgId the value for message.msg_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.userid
     *
     * @return the value of message.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.userid
     *
     * @param userid the value for message.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.num
     *
     * @return the value of message.num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.num
     *
     * @param num the value for message.num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.template
     *
     * @return the value of message.template
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.template
     *
     * @param template the value for message.template
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}