package com.github.flux.entity;

import java.io.Serializable;

public class MyAppointment implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_appointment.partake_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long myId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_appointment.appointment_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long appointmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_appointment.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_appointment.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_appointment.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

   


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_appointment.appointment_id
     *
     * @return the value of my_appointment.appointment_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getAppointmentId() {
        return appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_appointment.appointment_id
     *
     * @param appointmentId the value for my_appointment.appointment_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setAppointmentId(Long appointmentId) {
        this.appointmentId = appointmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_appointment.userid
     *
     * @return the value of my_appointment.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_appointment.userid
     *
     * @param userid the value for my_appointment.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_appointment.type
     *
     * @return the value of my_appointment.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_appointment.type
     *
     * @param type the value for my_appointment.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_appointment.create_time
     *
     * @return the value of my_appointment.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_appointment.create_time
     *
     * @param createTime the value for my_appointment.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

	public Long getMyId() {
		return myId;
	}

	public void setMyId(Long myId) {
		this.myId = myId;
	}

	@Override
	public String toString() {
		return "MyAppointment [myId=" + myId + ", appointmentId=" + appointmentId + ", userid=" + userid + ", type="
				+ type + ", createTime=" + createTime + "]";
	}
    
    
    
}