package com.github.flux.entity;

public class MyTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.my_task_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long myTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.task_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.reward_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long rewardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_task.receive_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long receiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.my_task_id
     *
     * @return the value of my_task.my_task_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getMyTaskId() {
        return myTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.my_task_id
     *
     * @param myTaskId the value for my_task.my_task_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setMyTaskId(Long myTaskId) {
        this.myTaskId = myTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.userid
     *
     * @return the value of my_task.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.userid
     *
     * @param userid the value for my_task.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.task_id
     *
     * @return the value of my_task.task_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.task_id
     *
     * @param taskId the value for my_task.task_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.reward_num
     *
     * @return the value of my_task.reward_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getRewardNum() {
        return rewardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.reward_num
     *
     * @param rewardNum the value for my_task.reward_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setRewardNum(Long rewardNum) {
        this.rewardNum = rewardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.status
     *
     * @return the value of my_task.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.status
     *
     * @param status the value for my_task.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.create_time
     *
     * @return the value of my_task.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.create_time
     *
     * @param createTime the value for my_task.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_task.receive_time
     *
     * @return the value of my_task.receive_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_task.receive_time
     *
     * @param receiveTime the value for my_task.receive_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setReceiveTime(Long receiveTime) {
        this.receiveTime = receiveTime;
    }
}