package com.github.flux.entity;

import java.io.Serializable;

public class PayLog implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.log_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.tran_no
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String tranNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.order_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.price
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_log.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.log_id
     *
     * @return the value of pay_log.log_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.log_id
     *
     * @param logId the value for pay_log.log_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.tran_no
     *
     * @return the value of pay_log.tran_no
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getTranNo() {
        return tranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.tran_no
     *
     * @param tranNo the value for pay_log.tran_no
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setTranNo(String tranNo) {
        this.tranNo = tranNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.order_id
     *
     * @return the value of pay_log.order_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.order_id
     *
     * @param orderId the value for pay_log.order_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.price
     *
     * @return the value of pay_log.price
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.price
     *
     * @param price the value for pay_log.price
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.status
     *
     * @return the value of pay_log.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.status
     *
     * @param status the value for pay_log.status
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_log.create_time
     *
     * @return the value of pay_log.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_log.create_time
     *
     * @param createTime the value for pay_log.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}