package com.github.flux.entity;

public class PrizeDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.detail_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.our_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.flow_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long flowNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.is_receive
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer isReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_detail.receive_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long receiveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.detail_id
     *
     * @return the value of prize_detail.detail_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.detail_id
     *
     * @param detailId the value for prize_detail.detail_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.our_id
     *
     * @return the value of prize_detail.our_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.our_id
     *
     * @param ourId the value for prize_detail.our_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setOutId(String outId) {
        this.outId = outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.userid
     *
     * @return the value of prize_detail.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.userid
     *
     * @param userid the value for prize_detail.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.flow_num
     *
     * @return the value of prize_detail.flow_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getFlowNum() {
        return flowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.flow_num
     *
     * @param flowNum the value for prize_detail.flow_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setFlowNum(Long flowNum) {
        this.flowNum = flowNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.create_time
     *
     * @return the value of prize_detail.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.create_time
     *
     * @param createTime the value for prize_detail.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.is_receive
     *
     * @return the value of prize_detail.is_receive
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getIsReceive() {
        return isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.is_receive
     *
     * @param isReceive the value for prize_detail.is_receive
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setIsReceive(Integer isReceive) {
        this.isReceive = isReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_detail.receive_time
     *
     * @return the value of prize_detail.receive_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getReceiveTime() {
        return receiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_detail.receive_time
     *
     * @param receiveTime the value for prize_detail.receive_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setReceiveTime(Long receiveTime) {
        this.receiveTime = receiveTime;
    }
}