package com.github.flux.entity;

public class PrizeOut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.our_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.sum_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long sumNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.out_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long outNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.out_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long outTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.return_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long returnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_out.return_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long returnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.our_id
     *
     * @return the value of prize_out.our_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.our_id
     *
     * @param ourId the value for prize_out.our_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setOurId(String outId) {
        this.outId = outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.userid
     *
     * @return the value of prize_out.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.userid
     *
     * @param userid the value for prize_out.userid
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.sum_num
     *
     * @return the value of prize_out.sum_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getSumNum() {
        return sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.sum_num
     *
     * @param sumNum the value for prize_out.sum_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setSumNum(Long sumNum) {
        this.sumNum = sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.out_num
     *
     * @return the value of prize_out.out_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getOutNum() {
        return outNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.out_num
     *
     * @param outNum the value for prize_out.out_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setOutNum(Long outNum) {
        this.outNum = outNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.out_time
     *
     * @return the value of prize_out.out_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.out_time
     *
     * @param outTime the value for prize_out.out_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setOutTime(Long outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.return_num
     *
     * @return the value of prize_out.return_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getReturnNum() {
        return returnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.return_num
     *
     * @param returnNum the value for prize_out.return_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setReturnNum(Long returnNum) {
        this.returnNum = returnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_out.return_time
     *
     * @return the value of prize_out.return_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_out.return_time
     *
     * @param returnTime the value for prize_out.return_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setReturnTime(Long returnTime) {
        this.returnTime = returnTime;
    }
}