package com.github.flux.entity;

import java.io.Serializable;

public class PrizePool implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_pool.pool_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long poolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_pool.sum_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long sumNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_pool.consumed
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long consumed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_pool.daily_max
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long dailyMax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize_pool.every_max
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long everyMax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_pool.pool_id
     *
     * @return the value of prize_pool.pool_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getPoolId() {
        return poolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_pool.pool_id
     *
     * @param poolId the value for prize_pool.pool_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setPoolId(Long poolId) {
        this.poolId = poolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_pool.sum_num
     *
     * @return the value of prize_pool.sum_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getSumNum() {
        return sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_pool.sum_num
     *
     * @param sumNum the value for prize_pool.sum_num
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setSumNum(Long sumNum) {
        this.sumNum = sumNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_pool.consumed
     *
     * @return the value of prize_pool.consumed
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getConsumed() {
        return consumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_pool.consumed
     *
     * @param consumed the value for prize_pool.consumed
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setConsumed(Long consumed) {
        this.consumed = consumed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_pool.daily_max
     *
     * @return the value of prize_pool.daily_max
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getDailyMax() {
        return dailyMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_pool.daily_max
     *
     * @param dailyMax the value for prize_pool.daily_max
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setDailyMax(Long dailyMax) {
        this.dailyMax = dailyMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize_pool.every_max
     *
     * @return the value of prize_pool.every_max
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getEveryMax() {
        return everyMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize_pool.every_max
     *
     * @param everyMax the value for prize_pool.every_max
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setEveryMax(Long everyMax) {
        this.everyMax = everyMax;
    }
}