package com.github.flux.entity;

public class ShopGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.goods_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.name
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.logo
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.price
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.stock
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.sold
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long sold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_goods.descn
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private String descn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.goods_id
     *
     * @return the value of shop_goods.goods_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.goods_id
     *
     * @param goodsId the value for shop_goods.goods_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.name
     *
     * @return the value of shop_goods.name
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.name
     *
     * @param name the value for shop_goods.name
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.logo
     *
     * @return the value of shop_goods.logo
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.logo
     *
     * @param logo the value for shop_goods.logo
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.type
     *
     * @return the value of shop_goods.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.type
     *
     * @param type the value for shop_goods.type
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.price
     *
     * @return the value of shop_goods.price
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.price
     *
     * @param price the value for shop_goods.price
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.stock
     *
     * @return the value of shop_goods.stock
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.stock
     *
     * @param stock the value for shop_goods.stock
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.sold
     *
     * @return the value of shop_goods.sold
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getSold() {
        return sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.sold
     *
     * @param sold the value for shop_goods.sold
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setSold(Long sold) {
        this.sold = sold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_goods.descn
     *
     * @return the value of shop_goods.descn
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public String getDescn() {
        return descn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_goods.descn
     *
     * @param descn the value for shop_goods.descn
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setDescn(String descn) {
        this.descn = descn;
    }
}