package com.github.flux.entity;

public class Sign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.sign_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long signId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.user_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.yyyymm
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer yyyymm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.yyyymmdd
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Integer yyyymmdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.sign_id
     *
     * @return the value of sign.sign_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getSignId() {
        return signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.sign_id
     *
     * @param signId the value for sign.sign_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setSignId(Long signId) {
        this.signId = signId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.user_id
     *
     * @return the value of sign.user_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.user_id
     *
     * @param userId the value for sign.user_id
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.yyyymm
     *
     * @return the value of sign.yyyymm
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getYyyymm() {
        return yyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.yyyymm
     *
     * @param yyyymm the value for sign.yyyymm
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setYyyymm(Integer yyyymm) {
        this.yyyymm = yyyymm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.yyyymmdd
     *
     * @return the value of sign.yyyymmdd
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Integer getYyyymmdd() {
        return yyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.yyyymmdd
     *
     * @param yyyymmdd the value for sign.yyyymmdd
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setYyyymmdd(Integer yyyymmdd) {
        this.yyyymmdd = yyyymmdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign.create_time
     *
     * @return the value of sign.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign.create_time
     *
     * @param createTime the value for sign.create_time
     *
     * @mbggenerated Thu Aug 13 21:52:06 CST 2015
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}